#!/usr/bin/env python3
"""
Content Generator Service for Telegram Affiliate Bot
Handles content generation using Google Sheets templates and AI rewriting.
"""

import random
from typing import Dict, List, Optional, Any
from services.sheets_api import sheets_api
from services.llm_client import OpenAIClient
from services.logger import bot_logger


class ContentGenerator:
    """Service for generating affiliate content using templates and AI."""

    def __init__(self):
        # Create LLM client dynamically to avoid caching issues
        self._llm_client = None
        self.templates_cache = {}
        self.hashtags_cache = {}
        self._load_templates()

    @property
    def llm_client(self):
        """Lazy initialization of LLM client."""
        if self._llm_client is None:
            from services.llm_client import OpenAIClient
            self._llm_client = OpenAIClient()
        return self._llm_client

    def _load_templates(self):
        """Load content templates from Google Sheets (hashtags removed - now generated by LLM)."""
        try:
            # Load content templates
            templates_data = sheets_api.get_sheet_data('content_templates')
            if templates_data and len(templates_data) > 1:
                headers = templates_data[0]
                col_indices = {header: idx for idx, header in enumerate(headers)}

                self.templates_cache = {}
                for row in templates_data[1:]:
                    if len(row) >= len(headers):
                        template_id = row[col_indices.get('template_id', 0)]
                        category = row[col_indices.get('category', 4)]
                        template_text = row[col_indices.get('template_text', 2)]
                        # Note: hashtags column removed - hashtags now generated by LLM

                        if category not in self.templates_cache:
                            self.templates_cache[category] = []

                        self.templates_cache[category].append({
                            'id': template_id,
                            'text': template_text,
                            # 'hashtags': hashtags  # Removed - now generated by LLM
                        })

            # Hashtags no longer loaded from Google Sheets - generated by LLM instead
            self.hashtags_cache = {}

            bot_logger.log_info("ContentGenerator", f"Loaded {len(self.templates_cache)} template categories (hashtags now generated by LLM)")

        except Exception as e:
            bot_logger.log_error("ContentGenerator", e, "Failed to load templates from Google Sheets")
            self.templates_cache = {}
            self.hashtags_cache = {}

    def get_random_template(self, category: str) -> Optional[Dict[str, str]]:
        """Get a random template for the specified category."""
        if category not in self.templates_cache:
            # Try to find a generic template or fallback
            if 'Electronics' in self.templates_cache:
                category = 'Electronics'
            else:
                return None

        templates = self.templates_cache[category]
        if not templates:
            return None

        return random.choice(templates)

    def get_hashtags_for_category(self, category: str) -> str:
        """Get hashtags for the specified category."""
        return self.hashtags_cache.get(category, '#Affiliate #Product')

    async def generate_content(self, product_data: Dict[str, Any], category: Optional[str] = None, language: str = 'it') -> Optional[Dict[str, str]]:
        """
        Generate content for a product using templates and AI rewriting with product data.

        Args:
            product_data: Product information dictionary (supports both legacy and enriched formats)
            category: Product category (optional, will be inferred from product_data)

        Returns:
            Dictionary with 'content' and 'hashtags' keys (hashtags generated by LLM)
        """
        try:
            # Determine category
            if not category:
                category = product_data.get('category', 'Electronics')

            # Get template
            template = self.get_random_template(category)
            if not template:
                bot_logger.log_error("ContentGenerator", Exception(f"No template found for category: {category}"), "Using fallback template")
                template = {
                    'text': 'Check out this amazing {product_name}! ⭐ {rating}/5 stars from {reviews_count} reviews. Get yours now: {affiliate_link}',
                }

            # Fill template variables - support both legacy and enriched data formats
            # Handle different key formats from various data sources
            product_name = (product_data.get('Title') or
                          product_data.get('title') or
                          product_data.get('name') or
                          product_data.get('product_name', 'Amazing Product'))

            # Handle rating - support both string and numeric formats
            rating_raw = (product_data.get('Rating') or
                         product_data.get('rating'))
            if rating_raw is not None and rating_raw != '' and rating_raw != 'None':
                try:
                    rating_val = float(rating_raw)
                    rating = f"{rating_val:.1f}"
                except (ValueError, TypeError):
                    rating = str(rating_raw)
            else:
                rating = '4.5'

            # Reviews are used for filtering only, not displayed in posts
            reviews_count = None

            # Handle price
            price_raw = (product_data.get('Price') or
                        product_data.get('price'))
            print(f"DEBUG: ContentGenerator - price_raw = {price_raw}, type = {type(price_raw)}")
            if price_raw is not None and price_raw != '' and price_raw != 'None':
                try:
                    # Handle decimal.Decimal, int, float types
                    from decimal import Decimal
                    if isinstance(price_raw, (int, float, Decimal)):
                        price = f"€{float(price_raw):.2f}"
                    else:
                        price = str(price_raw).strip()
                        # If it's already a formatted price string with Euro symbol, use it as-is
                        if not price.startswith('€'):
                            # Try to parse and format as Euro price
                            price_clean = price.replace('€', '').replace(',', '.').strip()
                            try:
                                price_val = float(price_clean)
                                price = f"€{price_val:.2f}"
                            except (ValueError, TypeError):
                                # If parsing fails, add Euro symbol
                                price = f"€{price}"
                except (ValueError, TypeError):
                    price = str(price_raw).strip()
            else:
                price = ''
            print(f"DEBUG: ContentGenerator - final price = '{price}'")

            affiliate_link = (product_data.get('AffiliateLink') or
                            product_data.get('affiliate_link') or
                            product_data.get('affiliate_link', '#'))

            # Format the template first
            template_text = template['text']
            content = template_text.format(
                product_name=product_name,
                rating=rating,
                reviews_count=reviews_count,
                affiliate_link=affiliate_link,
                price=price,
            )

            # Always add price information if available and not already in content
            if price and price != '' and f'Price: {price}' not in content and '💰' not in content:
                # Insert price after the product name/title
                lines = content.split('\n')
                if lines:
                    # Find the first line (usually the title) and add price after it
                    title_line = lines[0]
                    price_line = f'💰 **Price: {price}**'
                    lines.insert(1, price_line)
                    content = '\n'.join(lines)

            # Use AI to generate content with hashtags based on product data
            try:
                print(f"DEBUG: ContentGenerator - About to call _generate_content_with_product_data")
                final_content, generated_hashtags = await self._generate_content_with_product_data(product_data, content)
                print(f"DEBUG: ContentGenerator - LLM call returned: final_content={bool(final_content)}, hashtags='{generated_hashtags}'")
                if final_content:
                    print(f"DEBUG: ContentGenerator - Using AI-generated content: {final_content[:100]}...")
                    content = final_content
                    hashtags = generated_hashtags
                    # Ensure price is still in the content after AI rewriting
                    if price and price != '' and f'Price: {price}' not in content and '💰' not in content:
                        # Re-insert price if AI removed it
                        lines = content.split('\n')
                        if lines and len(lines) > 1:
                            # Insert price after the title line
                            lines.insert(1, f'💰 **Price: {price}**')
                            content = '\n'.join(lines)
                else:
                    # Fallback if AI generation fails
                    print(f"DEBUG: ContentGenerator - AI generation returned None, using fallback")
                    hashtags = '#Product #Affiliate'
            except Exception as e:
                print(f"DEBUG: ContentGenerator - AI content generation exception: {e}")
                bot_logger.log_error("ContentGenerator", e, "AI content generation failed, using fallback")
                hashtags = '#Product #Affiliate'

            # If we have features from API, add them as bullet points to the content
            features = product_data.get('features') or product_data.get('Features', [])
            if features and isinstance(features, list) and len(features) > 0:
                # Add top 2-3 features as bullet points
                feature_bullets = "\n\n" + "\n".join(f"• {feature.strip()}" for feature in features[:3])
                content += feature_bullets

            # Apply language translation if needed
            if language == 'ru':
                content = await self._translate_to_russian(content)
                hashtags = await self._translate_hashtags_to_russian(hashtags)

            # FINAL PRICE GUARANTEE: Ensure price is always included in the final content
            print(f"DEBUG: Final guarantee start - price = '{price}', content length = {len(content)}")
            try:
                if price and price != '':
                    lines = content.split('\n')
                    print(f"DEBUG: Final guarantee - content has {len(lines)} lines before processing")
                    # Remove any existing price lines to avoid duplicates
                    original_lines = len(lines)
                    lines = [line for line in lines if not (line.startswith('💰') or 'Price:' in line)]
                    removed_lines = original_lines - len(lines)
                    print(f"DEBUG: Final guarantee - removed {removed_lines} existing price lines")
                    # Insert price after the title (first line)
                    if lines:
                        lines.insert(1, f'💰 **Price: {price}**')
                        content = '\n'.join(lines)
                        print(f"DEBUG: Final guarantee - inserted price, content now has {len(lines)} lines")
                        print(f"DEBUG: Final guarantee - content after insertion: '{content[:300]}...'")
                    else:
                        print(f"DEBUG: Final guarantee - no lines to insert into")
                else:
                    print(f"DEBUG: Final guarantee - price is empty or None, skipping")
                print(f"DEBUG: Final guarantee end - final content preview: '{content[:200]}...'")
            except Exception as e:
                print(f"DEBUG: Final guarantee ERROR: {e}")
                # Emergency fallback: prepend price to content
                if price and price != '':
                    content = f'💰 **Price: {price}**\n\n{content}'
                    print(f"DEBUG: Final guarantee emergency fallback applied")

            return {
                'content': content,
                'hashtags': hashtags,
                'template_id': template.get('id', 'fallback'),
                'category': category
            }

        except Exception as e:
            bot_logger.log_error("ContentGenerator", e, f"Content generation failed for product: {product_data.get('title', product_data.get('Title', 'Unknown'))}")
            return None

    async def _generate_content_with_product_data(self, product_data: Dict[str, Any], base_content: str) -> tuple[Optional[str], str]:
        """Use AI to generate content and hashtags based on full product data."""
        try:
            # Get rewrite prompt from Google Sheets
            rewrite_prompt_data = sheets_api.get_sheet_data('rewrite_prompt')
            if rewrite_prompt_data and len(rewrite_prompt_data) > 1:
                base_prompt = rewrite_prompt_data[1][0]  # First row, first column
            else:
                base_prompt = "Rewrite the following text to make it engaging and persuasive and fit for a social media post."

            # Build comprehensive product information
            product_info = f"""
Product Name: {product_data.get('Title', product_data.get('name', 'Unknown Product'))}
Rating: {product_data.get('Rating', product_data.get('rating', 'N/A'))}/5 stars
Review Count: {product_data.get('ReviewsCount', product_data.get('reviews_count', 'N/A'))} reviews
Price: {product_data.get('Price', product_data.get('price', 'N/A'))}
Sales Rank: {product_data.get('SalesRank', product_data.get('sales_rank', 'N/A'))}
ASIN: {product_data.get('ASIN', product_data.get('asin', 'N/A'))}
"""

            # Enhanced prompt that includes product data and requests hashtags
            enhanced_prompt = f"""{base_prompt}

Product Information:
{product_info}

Base Content: {base_content}

Please rewrite this content to be engaging and persuasive for social media. Include relevant hashtags at the end of your response. Make sure the content highlights the product's key features, rating, and value proposition."""

            # Use the LLM to generate content with hashtags
            response = await self.llm_client.rewrite_text(enhanced_prompt, base_content)

            if response:
                # Try to separate content and hashtags
                # Look for hashtags at the end (starting with #)
                lines = response.strip().split('\n')
                content_lines = []
                hashtag_lines = []

                # Find where hashtags start
                for i, line in enumerate(lines):
                    if line.strip().startswith('#'):
                        hashtag_lines = lines[i:]
                        content_lines = lines[:i]
                        break
                else:
                    # No hashtags found, use whole response as content
                    content_lines = lines
                    hashtag_lines = []

                final_content = '\n'.join(content_lines).strip()
                hashtags = ' '.join(hashtag_lines).strip() if hashtag_lines else '#Product #Affiliate'

                return final_content, hashtags
            else:
                return None, '#Product #Affiliate'

        except Exception as e:
            bot_logger.log_error("ContentGenerator", e, "AI content generation with product data failed")
            return None, '#Product #Affiliate'

    async def _translate_to_russian(self, content: str) -> str:
        """Translate content to Russian using AI."""
        try:
            if not content or content.strip() == '':
                return content

            translation_prompt = f"""Translate the following Italian product description to Russian. Keep the structure and formatting intact, but translate all text to Russian. Maintain any emojis, special characters, and formatting:

{content}

Provide only the Russian translation, nothing else."""

            translated = await self.llm_client.rewrite_text(translation_prompt, content)
            if translated and len(translated.strip()) > 0:
                return translated.strip()
            else:
                # Fallback: return original content if translation fails
                bot_logger.log_error("ContentGenerator", Exception("Russian translation failed"), f"Returning original content: {content[:100]}...")
                return content

        except Exception as e:
            bot_logger.log_error("ContentGenerator", e, f"Russian translation failed for content: {content[:100]}...")
            return content

    async def _translate_hashtags_to_russian(self, hashtags: str) -> str:
        """Translate hashtags to Russian equivalents."""
        try:
            if not hashtags or hashtags.strip() == '':
                return '#Продукт #Партнер'

            # Common hashtag translations
            hashtag_translations = {
                '#Deal': '#Скидка',
                '#Product': '#Продукт',
                '#Affiliate': '#Партнер',
                '#Shopping': '#Покупки',
                '#Amazon': '#Амазон',
                '#Sale': '#Распродажа',
                '#Discount': '#Скидка',
                '#Offer': '#Предложение',
                '#Buy': '#Купить',
                '#Shop': '#Магазин',
                '#Price': '#Цена',
                '#Quality': '#Качество',
                '#Best': '#Лучший',
                '#New': '#Новый',
                '#Great': '#Отличный'
            }

            # Split hashtags and translate each one
            hashtag_list = hashtags.split()
            translated_hashtags = []

            for hashtag in hashtag_list:
                hashtag = hashtag.strip()
                if hashtag in hashtag_translations:
                    translated_hashtags.append(hashtag_translations[hashtag])
                else:
                    # For unknown hashtags, try AI translation
                    try:
                        translation_prompt = f"Translate this English hashtag to Russian: {hashtag}. Provide only the Russian hashtag starting with #, nothing else."
                        translated = await self.llm_client.rewrite_text(translation_prompt, hashtag)
                        if translated and translated.startswith('#'):
                            translated_hashtags.append(translated.strip())
                        else:
                            translated_hashtags.append(hashtag)  # Keep original if translation fails
                    except:
                        translated_hashtags.append(hashtag)  # Keep original if translation fails

            return ' '.join(translated_hashtags)

        except Exception as e:
            bot_logger.log_error("ContentGenerator", e, f"Hashtag translation failed for: {hashtags}")
            return '#Продукт #Партнер'

    async def generate_post_content(self, product_data: Dict[str, Any]) -> Optional[Dict[str, str]]:
        """
        Generate complete post content including text, hashtags, and metadata.

        Args:
            product_data: Product information from Amazon/Google Sheets

        Returns:
            Complete post data dictionary
        """
        try:
            content_result = await self.generate_content(product_data)

            if not content_result:
                # Return fallback content if generation failed - include price if available
                title = product_data.get('Title', product_data.get('title', 'Amazing Product'))
                price_raw = (product_data.get('Price') or product_data.get('price'))
                price_text = ""
                if price_raw is not None and price_raw != '' and price_raw != 'None':
                    try:
                        from decimal import Decimal
                        if isinstance(price_raw, (int, float, Decimal)):
                            price_text = f"💰 **Price: €{float(price_raw):.2f}**\n\n"
                        else:
                            price_clean = str(price_raw).replace('€', '').replace(',', '.').strip()
                            try:
                                price_val = float(price_clean)
                                price_text = f"💰 **Price: €{price_val:.2f}**\n\n"
                            except (ValueError, TypeError):
                                if str(price_raw).startswith('€'):
                                    price_text = f"💰 **Price: {price_raw}**\n\n"
                    except (ValueError, TypeError):
                        pass

                return {
                    'text': f"✨ **GREAT DEAL!** {title}\n\n{price_text}Check out this amazing product!",
                    'hashtags': '#Deal #Product #Affiliate',
                    'product_name': product_data.get('Title', product_data.get('title', '')),
                    'product_link': product_data.get('AffiliateLink', product_data.get('affiliate_link', '')),
                    'product_image': product_data.get('ImageURL', product_data.get('image_url', '')),
                    'rating': product_data.get('Rating', product_data.get('rating', '')),
                    'reviews_count': product_data.get('ReviewsCount', product_data.get('review_count', '')),
                    'category': 'General',
                    'template_id': 'fallback'
                }

            # Add additional metadata
            post_data = {
                'text': content_result['content'],
                'hashtags': content_result.get('hashtags', '#Product #Affiliate'),
                'product_name': product_data.get('Title', product_data.get('title', '')),
                'product_link': product_data.get('AffiliateLink', product_data.get('affiliate_link', '')),
                'product_image': product_data.get('ImageURL', product_data.get('image_url', '')),
                'rating': product_data.get('Rating', product_data.get('rating', '')),
                'reviews_count': product_data.get('ReviewsCount', product_data.get('review_count', '')),
                'category': content_result.get('category', 'General'),
                'template_id': content_result.get('template_id', 'fallback')
            }

            return post_data

        except Exception as e:
            bot_logger.log_error("ContentGenerator", e, "generate_post_content failed completely")
            # Ultimate fallback
            return {
                'text': f"✨ **GREAT DEAL!** {product_data.get('Title', product_data.get('title', 'Amazing Product'))}\n\nCheck out this amazing product!",
                'hashtags': '#Deal #Product #Affiliate',
                'product_name': product_data.get('Title', product_data.get('title', '')),
                'product_link': product_data.get('AffiliateLink', product_data.get('affiliate_link', '')),
                'product_image': product_data.get('ImageURL', product_data.get('image_url', '')),
                'rating': product_data.get('Rating', product_data.get('rating', '')),
                'reviews_count': product_data.get('ReviewsCount', product_data.get('review_count', '')),
                'category': 'General',
                'template_id': 'fallback'
            }


# Global instance - lazy initialization
_content_generator = None

def get_content_generator():
    """Get the global content generator instance with lazy initialization."""
    global _content_generator
    if _content_generator is None:
        _content_generator = ContentGenerator()
    return _content_generator

# For backward compatibility
content_generator = get_content_generator()
